version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: golfapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: ../backend
    command: flask run --host=0.0.0.0
    volumes:
      - ../backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/golfapp

volumes:
  pgdata:
